// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BilLibEF.model
{
    [Table("BilEjer")]
    public partial class BilEjer
    {
        public BilEjer()
        {
            Cars = new HashSet<Car>();
        }

        [Key]
        [StringLength(11)]
        public string Phone { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty(nameof(Car.EjerNavigation))]
        public virtual ICollection<Car> Cars { get; set; }
    }
}