// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BilLibEF.model
{
    [Table("Car")]
    public partial class Car
    {
        [Key]
        [StringLength(7)]
        public string RegNr { get; set; }
        [StringLength(15)]
        public string Colour { get; set; }
        public bool El { get; set; }
        [Required]
        [StringLength(11)]
        public string Ejer { get; set; }

        [ForeignKey(nameof(Ejer))]
        [InverseProperty(nameof(BilEjer.Cars))]
        public virtual BilEjer EjerNavigation { get; set; }
    }
}