// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace BilLibEF.model
{
    public partial class DemodbContext : DbContext
    {
        public DemodbContext()
        {
        }

        public DemodbContext(DbContextOptions<DemodbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<BilEjer> BilEjers { get; set; }
        public virtual DbSet<Car> Cars { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=DemoDB;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<BilEjer>(entity =>
            {
                entity.HasKey(e => e.Phone)
                    .HasName("PK__BilEjer__5C7E359F4FC16B65");
            });

            modelBuilder.Entity<Car>(entity =>
            {
                entity.HasKey(e => e.RegNr)
                    .HasName("PK__Car__2C6FF1E7C36731D7");

                entity.Property(e => e.RegNr).IsFixedLength(true);

                entity.HasOne(d => d.EjerNavigation)
                    .WithMany(p => p.Cars)
                    .HasForeignKey(d => d.Ejer)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Car__Ejer__398D8EEE");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}